language: cpp
compiler:
  - gcc
  - clang
addons:
  apt_packages: "curl"
before_install:
  # Get CMake 2.8
  - wget https://github.com/Viq111/travis-container-packets/releases/download/cmake-2.8.12/cmake.tar.bz2
  - tar -xjf cmake.tar.bz2
  - rm cmake.tar.bz2
  - export PATH=$(pwd)/cmake/bin:$PATH
  # Get new compiler
  - if [ "$CXX" == "g++" ]; then export COMPILER_NAME="gcc"; fi
  - if [ "$CXX" == "g++" ]; then export COMPILER_URL="https://github.com/Viq111/travis-container-packets/releases/download/gcc-4.8.2/gcc.tar.bz2"; fi
  - if [ "$CXX" == "clang++" ]; then export COMPILER_NAME="clang"; fi
  - if [ "$CXX" == "clang++" ]; then export COMPILER_URL="https://github.com/Viq111/travis-container-packets/releases/download/clang%2Blibcxx-3.4.2/clang_libcxx.tar.bz2"; fi
  # Get compiler
  - wget $COMPILER_URL
  - if [ "$CXX" == "clang++" ]; then mv clang_libcxx.tar.bz2 clang.tar.bz2; fi
  - tar -xjf $COMPILER_NAME.tar.bz2
  - rm $COMPILER_NAME.tar.bz2
  - if [ "$CXX" == "clang++" ]; then mv clang_libcxx clang; fi
  - export PATH=$(pwd)/$COMPILER_NAME/bin:$PATH
  - if [ "$COMPILER_NAME" == "gcc" ]; then export LIBRARY_PATH=$(pwd)/$COMPILER_NAME/lib64:$LIBRARY_PATH; fi
  - if [ "$COMPILER_NAME" == "clang" ]; then export LIBRARY_PATH=$(pwd)/$COMPILER_NAME/lib:$LIBRARY_PATH; fi
  - if [ "$COMPILER_NAME" == "gcc" ]; then export LD_LIBRARY_PATH=$(pwd)/$COMPILER_NAME/lib64:$LD_LIBRARY_PATH; fi
  - if [ "$COMPILER_NAME" == "clang" ]; then export LD_LIBRARY_PATH=$(pwd)/$COMPILER_NAME/lib:$LD_LIBRARY_PATH; fi
  - if [ "$COMPILER_NAME" == "gcc" ]; then export CPLUS_INCLUDE_PATH=$(pwd)/$COMPILER_NAME/include/c++/4.8.2:$CPLUS_INCLUDE_PATH; fi
  - if [ "$COMPILER_NAME" == "clang" ]; then export CPLUS_INCLUDE_PATH=$(pwd)/$COMPILER_NAME/include/c++/v1:$CPLUS_INCLUDE_PATH; fi
  - if [ "$COMPILER_NAME" == "clang" ]; then export CXXFLAGS="-stdlib=libc++"; fi
  - echo 'Compiling with:'
  - $CXX --version
  - which $CXX
  - $CC --version
  - which $CC
install:
  # Get boost
  - wget https://github.com/Viq111/static-files/releases/download/boost_1_57_travis/boost.tar.bz2
  - tar -xjf boost.tar.bz2
  - rm boost.tar.bz2
  - cd boost
  - export BOOST_ROOT=$(pwd)
  - cd $TRAVIS_BUILD_DIR
script: 
  - mkdir build && cd build
  - cmake ..
  - make
os:
  - linux
